:url = http://localhost:5013/upload
:apikey = 472abe203cd411e3a280ac162d80f1bf
:project-id = "9ead5bbf-f7eb-4010-bc1f-e4a063f56226",
:directory-id = "c54a77d6-cd6d-4cd1-8f19-44facc761da6",

POST :url?apikey=:apikey
Content-Type: application/json
{
        "project_id": :project-id
        "directory_id": :directory-id
        "filename": "abc.txt",
        "filesize": 10,
        "filemtime": "Thu, 30 Apr 2015 13:10:04 EST"
}


###

DELETE http://localhost:5013/upload/d8d1d87b-03f9-441a-8341-2a206263cd74?apikey=:apikey

###

PUT http://mctest.localhost/api/user/gtarcea@umich.edu/apikey
Content-Type: application/json
{
        "password": "password"
}
